### ISSUE TITLE
is there a file I should include

### ISSUE THREAD

**Issue by ahmedmibrahim** [fmilburn3/Energia_LPM#1]
Energia_LPM:27:14: error: 'sleep' was not declared in this scope
Energia_LPM:29:19: error: 'sleepSeconds' was not declared in this scope
Energia_LPM:32:11: error: 'suspend' was not declared in this scope
Energia_LPM:36:10: error: 'wakeup' was not declared in this scope

**Comment by fmilburn3** [comment]
You don’t say what microcontroller you are using.  I am no longer using Energia but the examples here were written for older MSP430 boards and no include was needed.  If the functions are not available then they most likely have not been implemented by the Energia developers.
